name: Upload to COS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Kodama & Typst
      run: |
        cargo install --git https://github.com/kokic/kodama.git
        sudo snap install typst
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Build with Kodama
      run: |
        kodama c -b $PAGE_URL
      env:
        PAGE_URL: www.arbustum-intelligens.xyz
    - name: Install coscmd
      run: sudo pip install coscmd
    - name: Configure coscmd
      env:
        SECRET_ID: ${{ secrets.SECRETID }}
        SECRET_KEY: ${{ secrets.SECRETKEY }}
        BUCKET: test-1301337442
        REGION: ap-tokyo
        PAGE_URL: www.arbustum-intelligens.xyz
      run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
    - name: Upload
      run: coscmd upload -rs --delete -f ./publish /